# Generated by Django 4.0.4 on 2022-04-21 13:36

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='body',
            field=wagtail.core.fields.StreamField([('HeroText', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.RichTextBlock(default='Title', required=False)), ('description', wagtail.core.blocks.RichTextBlock(default='Description', required=False)), ('button', wagtail.core.blocks.CharBlock(default='Button', required=False))]))], null=True),
        ),
    ]
